import type { Metadata } from "next";
import "./globals.css";
import { ReactQueryProvider } from "@/utils/ProviderReactQuery";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children}: { children: React.ReactNode}) {
  return (
    <ReactQueryProvider>
      <html lang="en">
        <body
          className={`antialiased`}
        >
          <Header/>
          {children}
        </body>
      </html>
    </ReactQueryProvider>
  );
}
